language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g gulp
script: gulp
after_script:
  - istanbul cover ./node_modules/jasmine-node/bin/jasmine-node --captureExceptions test/ && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
